# Generated by Django 5.2.3 on 2025-06-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_reserva_codigo_reserva_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('pasajero', 'vuelo'), name='reserva_unica_por_pasajero_y_vuelo'),
        ),
    ]
