# Generated by Django 5.2.3 on 2025-06-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_reserva_reserva_unica_por_pasajero_y_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
